name: E2E Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  playwright:
    name: Playwright Tests
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      env:
        SWAG_LABS_USERNAME: ${{ secrets.SWAG_LABS_USERNAME }}
        SWAG_LABS_PASSWORD: ${{ secrets.SWAG_LABS_PASSWORD }}
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-results
        path: playwright-report/
        retention-days: 10

  cucumber:
    name: Cucumber Tests
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browser
      run: npx playwright install chromium
    - name: Run Cucumber tests
      run: npm run test:cucumber
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: cucumber-results
        path: cucumber-report/
        retention-days: 10
